# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 342bc80c8e3f0a8dcddf90461ebd15c866d48d79d33dbfaf38ee894934118d9d57d1cd4edd9bd9b95253a1e253530f2d74ef89dc4350b7ba774cc231281510e1

test:
  secret_key_base: 1d0667559ad7bc39e48cf37351b871d1b74a173fcc6345901d154bdb5db9cb223914fb06dfdcce1c1d1322a678bba108a92f0567a7d6078b8b9a44c56053dc5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
